import { baseUrl } from "../constants/index";
const API = Object.freeze({
  getCaptcha: "/api/captcha?code=",
  // login: "/passport/local",
  // loginByToken: '/accessToken',
  login: `${baseUrl}/user/login`,
  register: `${baseUrl}/signup`,
  exportdata: `${baseUrl}/users/export/`,
  cryptocurrency: `${baseUrl}/cryptocurrency/market`,
  topCryptocurrency: `${baseUrl}/cryptocurrency/top`,
  historical: `${baseUrl}/history/latest`,
  serviceEngineersList: `${baseUrl}/users/engineers/`,
  users: `${baseUrl}/users`,
  addUser: `${baseUrl}/user/save`,
  editUser: `${baseUrl}/user/save/`,
  deleteUser: `${baseUrl}/user/`,
  polllist: `${baseUrl}/poll-list`,
  currentuser: `${baseUrl}/user/`,
  pollNotification: `${baseUrl}/user-notification/`,
  addBoilerBrand: `${baseUrl}/boiler/brand/save/`,
  editBoilerBrand: `${baseUrl}/boiler/brand/save/`,
  deleteBoilerBrand: `${baseUrl}/boiler/brand/`,
  getBoilerBrand: `${baseUrl}/boiler/brands/`,
  getBoilerModel: `${baseUrl}/boiler/models/`,
  addBoilerModel: `${baseUrl}/boiler/model/save/`,
  editBoilerModel: `${baseUrl}/boiler/model/save/`,
  deleteBoilerModel: `${baseUrl}/boiler/model/`,

  selectOption: `${baseUrl}/boiler/mgmt/details/`,
  // addBoiler:`${baseUrl}/create/boiler/`,

  getBoilerType: `${baseUrl}/boiler/types/`,
  addBoilerType: `${baseUrl}/boiler/type/save/`,
  editBoilerType: `${baseUrl}/boiler/type/save/`,
  deleteBoilerType: `${baseUrl}/boiler/type/`,

  addBoiler: `${baseUrl}/boiler/details/save/`,
  editBoiler: `${baseUrl}/boiler/details/save/:id`,
  editBoilerSub: `${baseUrl}/boiler/details/save/`,
  getBoiler: `${baseUrl}/boilers/`,
  deleteBoiler: `${baseUrl}/boiler/details/`,
  boilerById: `${baseUrl}/boiler/`,

  addService: `${baseUrl}/boiler/service/save/`,
  // editService: `${baseUrl}/boiler/details/save/:id`,
  editServiceSub: `${baseUrl}/boiler/details/save/`,
  getService: `${baseUrl}/boiler/service/details/`,
  deleteService: `${baseUrl}/boiler/service/`,
  serviceById: `${baseUrl}/boiler/service/detail/`,
  servicePostcode: `${baseUrl}/boiler/postcode/`,

  getFuelType: `${baseUrl}/fuel/types/`,
  addFuelType: `${baseUrl}/fuel/type/save/`,
  editFuelType: `${baseUrl}/fuel/type/save/`,
  deleteFuelType: `${baseUrl}/fuel/type/`,

  updateuser: `${baseUrl}/user/`,
  ediUsersDetails: `${baseUrl}/admin/user/`,
  question: `${baseUrl}/question-list`,
  pollresult: `${baseUrl}/poll-result/`,
  removeAvatar: `${baseUrl}/avatar/user/`,
  refcommunity: `${baseUrl}/community/referral/`,
  individualStatistics: `${baseUrl}/individual-statistics/`,
  communityStatistics: `${baseUrl}/community-statistics/`,
  singlepollresult: `${baseUrl}/poll-result/single/`,
  forgotpassword: `${baseUrl}/forgot/password`,
  resetpassword: `${baseUrl}/reset-password/`,
  updateuserpass: `${baseUrl}/change-password/`,
  addcommunity: `${baseUrl}/add-community`,
  community: `${baseUrl}/community/`,
  takePoll: `${baseUrl}/take-poll`,
  firstpoll: `${baseUrl}/get-questions/`,
  firstpollget: `${baseUrl}/get-question/`,
  addfirstpoll: `${baseUrl}/add-questions`,
  loginByToken: "/login",
  logout: "/logout",
  getSystemInfo: "/system/info",
  updateUser: "/user/update",
  getUserConfig: "/userConfig",
  reminder: "/reminder",
  todayTask: "/task",
  capitalFlowType: "/capitalFlowType",
  capitalFlow: "/capitalFlow",
  getCapitalFlowPrice: "/capitalFlow/price",
  memorandum: "/memorandum",
  innerMessage: "/innerMessage",
  todoList: "/todoList",
  getPanelData: "/panel",
  verifyEmailAccount: `${baseUrl}/email-verify/`,
  loginOtpVerify: `${baseUrl}/verify/otp`,
  serviceBoilerModels: `${baseUrl}/boiler/models/`,
  
});

export default API;
